import { SelectOption } from 'rizzui';

export const countryOptions: SelectOption[] = [
  { value: 'HU', label: 'Magyarország' },
  { value: 'AT', label: 'Ausztria' },
  { value: 'BE', label: 'Belgium' },
  { value: 'BG', label: 'Bulgária' },
  { value: 'HR', label: 'Horvátország' },
  { value: 'CY', label: 'Ciprus' },
  { value: 'CZ', label: 'Csehország' },
  { value: 'DK', label: 'Dánia' },
  { value: 'EE', label: 'Észtország' },
  { value: 'FI', label: 'Finnország' },
  { value: 'FR', label: 'Franciaország' },
  { value: 'DE', label: 'Németország' },
  { value: 'GR', label: 'Görögország' },
  { value: 'IE', label: 'Írország' },
  { value: 'IT', label: 'Olaszország' },
  { value: 'LV', label: 'Lettország' },
  { value: 'LT', label: 'Litvánia' },
  { value: 'LU', label: 'Luxemburg' },
  { value: 'MT', label: 'Málta' },
  { value: 'NL', label: 'Hollandia' },
  { value: 'PL', label: 'Lengyelország' },
  { value: 'PT', label: 'Portugália' },
  { value: 'RO', label: 'Románia' },
  { value: 'SK', label: 'Szlovákia' },
  { value: 'SI', label: 'Szlovénia' },
  { value: 'ES', label: 'Spanyolország' },
  { value: 'SE', label: 'Svédország' },
];

export const statusOptions: SelectOption[] = [
  { label: 'Új munkalap', value: 'new' },
  { label: 'Folyamatban', value: 'pending' },
  { label: 'Elkészült', value: 'completed' },
  { label: 'Aláírás alatt', value: 'outforsignature' },
  { label: 'Vázlat', value: 'draft' },
  { label: 'Lezárt', value: 'closed' },
];

export const priorityOptions: SelectOption[] = [
  { label: 'Leggyengébb', value: 'weakest' },
  { label: 'Gyenge', value: 'weak' },
  { label: 'Normál', value: 'normal' },
  { label: 'Erős', value: 'strong' },
  { label: 'Legerősebb', value: 'strongest' },
];

export const timeOptions: SelectOption[] = [
  { label: '00:00', value: '00:00:00' },
  { label: '01:00', value: '01:00:00' },
  { label: '02:00', value: '02:00:00' },
  { label: '03:00', value: '03:00:00' },
  { label: '04:00', value: '04:00:00' },
  { label: '05:00', value: '05:00:00' },
  { label: '06:00', value: '06:00:00' },
  { label: '07:00', value: '07:00:00' },
  { label: '08:00', value: '08:00:00' },
  { label: '09:00', value: '09:00:00' },
  { label: '10:00', value: '10:00:00' },
  { label: '11:00', value: '11:00:00' },
  { label: '12:00', value: '12:00:00' },
  { label: '13:00', value: '13:00:00' },
  { label: '14:00', value: '14:00:00' },
  { label: '15:00', value: '15:00:00' },
  { label: '16:00', value: '16:00:00' },
  { label: '17:00', value: '17:00:00' },
  { label: '18:00', value: '18:00:00' },
  { label: '19:00', value: '19:00:00' },
  { label: '20:00', value: '20:00:00' },
  { label: '21:00', value: '21:00:00' },
  { label: '22:00', value: '22:00:00' },
  { label: '23:00', value: '23:00:00' },
];
